### ISSUE TITLE
`ERROR` on `COUNT(DISTINCT tbl.field)`

### ISSUE THREAD

**Issue by LeoniePhiline** [DerekStride/tree-sitter-sql#154] opened 2023-06-19 16:54 UTC
![image](https://github.com/DerekStride/tree-sitter-sql/assets/22329650/ab715000-55c5-4f46-be63-8ab682768bd3)

Tree-sitter syntax error for `tbl` and `field` in:

```sql
SELECT
  COUNT(DISTINCT `tbl`.`field`)
FROM
  whatever;
```

**Comment by matthias-Q** [comment] 2023-06-19 17:16
I think this issue may be resolved when #150 is merged. The issue is that the `term` can be a `field` and there we have issue when the `field` is like scm.tbl.col.


Just to recap the tree here:
`invocation` -> `_select_expression` -> `term` -> `_expression` -> `field` -> [schema: `_alias_identifier`.][table_alias: `_alias_identifier`.]`identifier`

`_alias_identifier` -> `identifier` -> \``_idenfier`\`

So technically, I am a bit surprised that is does not work at the moment.

**Comment by LeoniePhiline** [comment] 2023-06-19 17:41
Ah yes. I did not pay attention to `DISTINCT`, since it did not error out. My mistake in not pointing that out!

`DISTINCT` is indeed mis-identified as `"identifier"`:

![image](https://github.com/DerekStride/tree-sitter-sql/assets/22329650/654411a1-26ec-4384-9320-b584ae246779)

**Comment by matthias-Q** [comment] 2023-06-19 17:42
I am preparing a fix right now

**Closed** 2023-06-19 18:47 UTC
